config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'items#index'
  resources :items do
    get '/buycheck', controller: 'items', action: 'buycheck'
    post '/payment', controller: 'items', action: 'payment'
    #Ajaxで動くアクションのルートを作成
    collection do
      get 'category' 
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
    end
  end
  resources :users, only: :index
  get 'users/:name', controller: 'users', action: 'show'
  get 'users/:name', controller: 'users', action: 'edit'
  
  resources :card, only: [:index, :new, :show, :destroy] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
    end
  end
  resources :categories, only: :index

end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  has_many :comment
  has_many :likes, dependent: :destroy
  has_many :images, dependent: :destroy
  belongs_to :buyer, class_name: "User", optional: true
  belongs_to :seller, class_name: "User", optional: true
  belongs_to :category
  belongs_to :brand, optional: true
  accepts_nested_attributes_for :images, allow_destroy: true

  validates :seller_id, presence: true
  validates :name, presence: true, length: { in: 1..40 }
  validates :price, presence: true, numericality: { only_integer: true }, inclusion: { in: 300..9999999 }
  validates :category_id, presence: true
  validates :description, presence: true
  validates :condition, presence: true
  validates :delivery_charge, presence: true
  validates :delivery_day, presence: true
  validates :prefecture_id, presence: true
  validates :size, presence: true
  validates :state, presence: true, inclusion: { in: [true, false] }
  validates :images, presence: true

  def self.search(search)
    return Item.all unless search
    Item.where('name LIKE(?)', "%#{search}%")
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  require 'payjp'

  before_action :set_find,only:[:show, :destroy, :edit, :update]
  before_action :move_to_session, only: [:buycheck, :payment, :new, :edit]
  before_action :bought_item_check, only: :buycheck
  before_action :correct_user, only: [:edit]

  def index
    @items = Item.includes(:images, :category, :seller).order(created_at: :desc) 
    @parents = Category.all.order("id ASC").limit(13)
  end

  def category
    @categories = Category.where(ancestry: nil)
    respond_to do |format|
      format.json
    end
  end
  
  def new
    @item = Item.new
    @item.images.build
      @category_parent_array = Category.where(ancestry: nil).pluck(:name)
      @category_parent_array.unshift("選択してください")
  end
  
  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def create
    @item = Item.new(item_params)
    @category_parent_array = Category.where(ancestry: nil).pluck(:name)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  
  def show
    @items = Item.includes(:images)
    @user = User.find(@item.seller_id)
  end

  def search
    @items = Item.search(params[:keyword])
    if @items[0] == nil
      redirect_to root_path
    end
  end

  def destroy
    @item.destroy
    redirect_to root_path
  end

  def buycheck
    @item = Item.find(params[:item_id])
    @items = Item.includes(:images)
    set_address
    if current_user.cards.blank?
      render :buycheck
    else
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_PRIVATE_KEY)
      card_info1 = Payjp::Customer.retrieve(current_user.cards.first.customer_id)
      @default_card_information = card_info1.cards.retrieve(current_user.cards.first.card_id)
      card_info2 = Payjp::Customer.retrieve(current_user.cards.last.customer_id) if current_user.cards.count == 2
      @second_card_information = card_info2.cards.retrieve(current_user.cards.last.card_id) if current_user.cards.count == 2
    end
  end

  def payment
    if params[:paycheck].blank? || params[:shipping_method].blank?
      redirect_to item_buycheck_path and return
    end
    item = Item.find(params[:item_id])
    card = set_payment_card
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_PRIVATE_KEY)
    charge = Payjp::Charge.create(amount: item.price, card: card.card_id, currency: 'jpy', customer: card.customer_id)
    item[:buyer_id] = current_user.id
    if item.save
      redirect_to root_path
    else
      redirect_to item_buycheck_path
    end
  rescue Payjp::CardError
    flash[:alert] = "※※※このカードは使用できません。別のカードを使用して下さい※※※"
    redirect_to item_buycheck_path
  end

  def edit
    @item.images
    @category_parent_array = Category.where(ancestry: nil).pluck(:name)
    grandchild_category = @item.category
    child_category = grandchild_category.parent

    @category_parent_array = []
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end

    @category_children_array = []
    Category.where(ancestry: child_category.ancestry).each do |children|
    @category_children_array << children
    end

    @category_grandchildren_array = []
    Category.where(ancestry: grandchild_category.ancestry).each do |grandchildren|
    @category_grandchildren_array << grandchildren
    end 
  end

  def update
    @category_parent_array = Category.where(ancestry: nil).pluck(:name)
    if @item.update(item_params)
      redirect_to root_path
    else
      redirect_to edit_item_path
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :price, :description, :condition, :delivery_charge, :delivery_day, :size, :prefecture_id, :category_id, :brand_id, images_attributes: [:image, :image_cache, :id ,:_destroy]).merge(seller_id: current_user.id, state: true)

  end

  def move_to_session
    redirect_to new_user_session_path unless user_signed_in?
  end

  def set_address
    @address = Address.find_by(user_id: current_user.id)
    @prefecture = Prefecture.find(@address.prefecture_id)
  end

  def set_payment_card
    if params[:shipping_method] == "card2"
      card = Card.where(user_id: current_user.id).second
    else
      card = Card.where(user_id: current_user.id).first
    end
  end

  def set_find
    @item = Item.find(params[:id])
  end

  def move_to_session
    redirect_to new_user_session_path unless user_signed_in?
  end
  
  def bought_item_check
    @item = Item.find(params[:item_id])
    redirect_to root_path unless @item.buyer_id.blank?
  end

  def correct_user
    @item = Item.find(params[:id])
    redirect_to root_path if current_user.id != @item.seller_id
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_footer.html.haml
.footer
  %ul.content
    %li.content__li
      %h2.content__li__head FURIMAについて
      %ul
        %li.content__li__head__list 会社概要（運営会社)
        %li.content__li__head__list プライバシーポリシー
        %li.content__li__head__list FURIMA利用規約
        %li.content__li__head__list ポイントに関する規約
    %li.content__li
      %h2.content__li__head FURIMAを見る
      %ul
        %li.content__li__head__list カテゴリー一覧
        %li.content__li__head__list ブランド一覧
    %li.content__li
      %h2.content__li__head ヘルプ&ガイド
      %ul
        %li.content__li__head__list FURIMAガイド
        %li.content__li__head__list FURIMAロゴ利用ガイドライン
        %li.content__li__head__list お知らせ
  .footer__logo
    .footer__logo__box
      = link_to root_path do
        = image_tag "logo/logo-white.png"
      %p.footer__logo__box @FURIMA

app/views/items/_form.html.haml
.upform
  - breadcrumb :former
  = breadcrumbs separator: " &rsaquo; "
  = form_with model: @item, local: true, method: "POST" do |f|
    .upform__picture
      .upform__picture__title 出品画像
      .upform__picture__mark 必須
      - if @item.errors.include?(:images)
        %p.upform_error 画像がありません
      .upform__picture__text ・最大5枚までアップロードできます。
      #image-box-1
        .item-num-0#image-box__container
          = f.fields_for :images do |i|
            .input-area
              = i.file_field :image, type: 'file', name: "item[images_attributes][][image]", value:"", style: "display:none", id:"img-file"
              %label{for: "img-file"}
                = icon('fas', 'camera', class: 'icon')
                .text 画像を選択して下さい。
                %i.fas.fa-image

    .upform__itemname
      .upform__itemname__title 商品名
      .upform__itemname__mark 必須
      - if @item.errors.include?(:name)
        %p.upform_error 入力して下さい
      .upform__itemname__name
        = f.text_field :name, class: "input_itemName", placeholder: "40文字まで"
      .upform__itemname__secondtitle 商品の説明
      .upform__itemname__secondmark 必須
      - if @item.errors.include?(:description)
        %p.upform_error 入力して下さい
      .upform__itemname__secondname
        = f.text_field :description, class: "input_itemDescription", placeholder: "( 色・素材・重さ・定価・注意点など )"
      .upform__itemname__thirdtitle 商品のサイズ
      .upform__itemname__thirdmark 必須
      - if @item.errors.include?(:size)
        %p.upform_error 入力して下さい
      .upform__itemname__thirdname 
        = f.text_field :size, class: "input_itemSize", placeholder: "( たて × よこ、S・M・Lなど )"
    .upform__itemdate
      .upform__itemdate__toptitle 商品の詳細
      .listing-product-detail__category
        .upform__itemdate__title カテゴリー
        .upform__itemdate__mark 必須
        - if @item.errors.include?(:category_id)
          %p.upform_error 選択して下さい
        .listing-select-wrapper
          .listing-select-wrapper__box
            .category__form
              = f.select :category_id, @category_parent_array, {}, {class: 'listing-select-wrapper__box--select', id: 'parent_category'}
      .upform__itemdate__secondtitle ブランド
      .upform__itemdate__secondmark 任意
      .upform__itemdate__brandname
        %input{placeholder: "選択してください"}
      .upform__itemdate__thirdtitle 商品の状態
      .upform__itemdate__thirdmark 必須
      - if @item.errors.include?(:condition)
        %p.upform_error 選択して下さい
      .upform__itemdate__condition
        = f.select :condition, [["&nbsp;&nbsp;選択して下さい".html_safe, nil],["新品、未使用","新品、未使用"],["未使用に近い","未使用に近い"],["目立った傷や汚れなし","目立った傷や汚れなし"],["やや傷や汚れあり","やや傷や汚れあり"],["傷や汚れあり","傷や汚れあり"],["全体的に状態が悪い","全体的に状態が悪い"]]
    .upform__delivery
      .upform__delivery__toptitle 配送について
      .upform__delivery__title 送料の負担
      .upform__delivery__mark 必須
      - if @item.errors.include?(:delivery_charge)
        %p.upform_error 選択して下さい
      .upform__delivery__postage
        = f.select :delivery_charge, [["&nbsp;&nbsp;選択して下さい".html_safe, nil],["送料込み（出品者負担）","送料込み（出品者負担）"],["着払い（購入者負担）","着払い（購入者負担）"]]
      .upform__delivery__secondtitle 発送元の地域
      .upform__delivery__secondmark 必須
      - if @item.errors.include?(:prefecture_id)
        %p.upform_error 選択して下さい
      .upform__delivery__area
        = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {include_blank: "---"}, {class: "input_itemRegion"}#地域ができたら変更
      .upform__delivery__thirdtitle 発送までの日数
      .upform__delivery__thirdmark 必須
      - if @item.errors.include?(:delivery_day)
        %p.upform_error 選択して下さい
      .upform__delivery__days
        = f.select :delivery_day, [["&nbsp;&nbsp;選択して下さい".html_safe, nil],["１〜２日で発送","１〜２日で発送"],["２〜３日で発送","２〜３日で発送"],["４〜５日で発送","４〜５日で発送"]]
      
    .upform__price
      .upform__price__toptitle 価格（¥300〜9,999,999） 半角で入力して下さい
      - if @item.errors.include?(:price)
        %p.upform_error_price 300~9,999,999の範囲で半角で入力して下さい
      .upform__price__title 販売価格
      .upform__price__mark 必須
      .upform__price__yenmark ￥
      .upform__price__saleprice
        = f.number_field :price, class: "input_sellprice", placeholder: "0" 
      .upform__price__secondtitle 販売手数料（10%）
      .upform__price__minuskey ー
      .upform__price__underline
      .upform__price__thirdtitle 販売利益
      .upform__price__secondminuskey ー
      
    .upform__itemupper
      .upform__itemupper__button
        = f.submit '出品する',  class: "submit-btn", data: { disable_with: '問い合わせ中...' }

  .upform__returnkey
    .upform__returnkey__button
      = link_to root_path do
        %p.group__btn もどる

app/views/items/_header.html.haml
- if user_signed_in?
  = render "items/login_user_header"
- else
  = render "items/no_login_user_header"

app/views/items/_miniheader.html.haml
.miniheader
  .miniheader__main
    .miniheader__main__inner
      .miniheader__main__inner__icon
        = link_to root_path do
          = image_tag "logo/logo.png"
      

app/views/items/_no_login_user_header.html.haml
.nologin
  .nologin__main
    .nologin__main__inner
      .nologin__main__inner__icon
        = link_to image_tag "logo/logo.png"
      .nologin__main__inner__key
        = form_with(url: search_items_path, local: true, method: :get) do |s|
          = s.text_field :keyword, placeholder: "キーワードから探す", class: "nologin__main__inner__key__search"
          = s.submit "検索", class: "nologin__main__inner__key__submit"
          = icon("fa", "search", class: "nologin__main__inner__key__icon")
    .nologin__main__bottom
      .login__main__bottom__left
        %ul.login__main__bottom__left__ul
          %li.login__main__bottom__left__ul__list1
            = link_to 'カテゴリー', categories_path, id: 'catBtn'
            = render  "items/nav-category", parent: @parents
          %li.nologin__main__bottom__left__ul__list ブランド
      .nologin__main__bottom__right
        %ul.nologin__main__bottom__right__ul
          %li.nologin__main__bottom__right__ul__list 
          = link_to "ログイン", new_user_session_path
          %li.nologin__main__bottom__right__ul__list 
          = link_to "新規登録", new_user_registration_path

app/views/items/_shuppin.html.haml
.camera
  .camera__box
    %span.camera__box__text 出品する
    = link_to new_item_path, class:"camera__box__link" do
      = image_tag "icon/icon_camera.png" 

app/views/items/edit.html.haml
.item_up
  .item_up__header
    = render "miniheader"

  .item_up__form
    = render "edit_form"

  .item_up__footer
    = render "footer"

app/views/items/index.html.haml
.wrapper
  = render "header"
  .main
    .main__section
      .main__section__center
        %h1.main__section__center__h1 人生を変えるフリマアプリ
        %p.main__section__center__p1 FURIMAは誰でもかんたんに出品・購入できる
        %p.main__section__center__p2 フリマアプリです
        .main__section__center__box
          .main__section__center__box__logo
          .main__section__center__box__logo1
          
    .main__section1
      %h2.main__section1__middle 
        FURIMAが選ばれる3つの理由
      .main__section1__line
      %ul.main__section1__box
        .main__section1__box__main1
          .main__section1__box__main1__text1 
            .main__section1__box__main1__text1__num 1
          %b.main__section1__box__main1__under 3分
          %b.main__section1__box__main1__bottom ですぐに出品
          %p.main__section1__box__main1__letter1 スマホで入力するだけで簡単に出品できる！

        .main__section__box__main2
          .main__section1__box__main2__text2 
            .main__section1__box__main2__text2__num 2
          %b.main__section1__box__main2__under シンプル
          %b.main__section1__box__main2__bottom で使いやすい
          %p.main__section1__box__main2__letter2 めんどくさい入力は必要なく、検索も購入もスムーズ！

        .main__section__box__main3
          .main__section1__box__main3__text3 
            .main__section1__box__main3__text3__num 3
          %b.main__section1__box__main3__under 手数料
          %b.main__section1__box__main3__bottom 業界最安
          %p.main__section1__box__main3__letter3 最大3%でお得に出品&購入！

    .main__section2
      .main__section2__center
        %h1.main__section2__center__h1 会員数日本一位
        %p.main__section2__center__p1 
          FURIMAは、フリマアプリで最も人気。
          %br 
          出品・購入回数も業界最多です！
          %br 
          ほしかったあの商品に出会えるかもしれません。
        .main__section2__center__box
          .main__section2__center__box__logo
          .main__section2__center__box__logo1

    .main__section3
      %h2.main__section3__middle 
        FURIMAの特徴
      .main__section3__line
      %ul.main__section3__box
        .main__section3__box__main1
          .main__section3__box__main1__text1 
          .main__section3__box__main1__num 簡単に売り買いできる
          %p.main__section3__box__main1__under 
            スマホひとつで、いつでもどこでも簡単
            %br 
            に出品・購入が可能！
        .main__section3__box__main2
          .main__section3__box__main2__text2 
          .main__section3__box__main2__num 売上金は即日振込みに対応
          %p.main__section3__box__main2__under 
            午前9時までに振込を依頼いただけれ
            %br 
            ば、翌日に指定の口座に入金いたします!
            
        .main__section3__box__main3
          .main__section3__box__main3__text3 
          .main__section3__box__main3__num 様々な支払いに対応
          %p.main__section3__box__main3__under 
            お支払いは、クレジットカードだけでなく、
            %br 
            ポイントや売上金など多彩な方法が
            %br 
            あります。
    .main__section4
      .main__section4__box
        %h2.main__section4__box__title ピックアップカテゴリー
        .main__section4__box__main
          .main__section4__box__main__sub 新規投稿商品
          .main__section4__box__main__product
            - @items.first(3).each do |item|
              = link_to item_path "#{item.id}" do
                .main__section4__box__main__product__lists1
                  -if item.buyer_id.present? 
                    .items-box_photo__sold
                      .items-box_photo__sold__inner
                        SOLD
                  .main__section4__box__main__product__lists1__image
                    = image_tag "#{item.images.first.image}" 
                    .main__section4__box__main__product__lists1__list
                      .main__section4__box__main__product__lists1__list__text
                        = item.name
                      .main__section4__box__main__product__lists1__list__text1 
                        .main__section4__box__main__product__lists1__list__text1__left
                          = item.price
                          円
                        .main__section4__box__main__product__lists1__list__text1__right ★ 0
                      .main__section4__box__main__product__lists1__list__text2 (税込み)
      .main__section4__box1
        %h2.main__section4__box1__title ピックアップブランド
        .main__section4__box1__main
          .main__section4__box1__main__sub アーカイバ
          .main__section4__box1__main__product
            - @items.first(3).each do |item|
              = link_to item_path(item.id) do
                .main__section4__box__main__product__lists1
                  -if item.buyer_id.present? 
                    .items-box_photo__sold
                      .items-box_photo__sold__inner
                        SOLD
                  .main__section4__box__main__product__lists1__image 
                    = image_tag "#{item.images.first.image}"
                    .main__section4__box__main__product__lists1__list
                      .main__section4__box__main__product__lists1__list__text
                        = item.name
                      .main__section4__box__main__product__lists1__list__text1 
                        .main__section4__box__main__product__lists1__list__text1__left
                          = item.price
                          円
                          .main__section4__box__main__product__lists1__list__text1__right ★ 0
                        .main__section4__box__main__product__lists1__list__text2 (税込み)

    .main__section5
      .main__section5__center
      %h1.main__section5__center__h1 だれでもかんたん、人生を変えるフリマアプリ
      %p.main__section5__center__p1 
        今すぐ無料ダウンロード
        .main__section5__center__box
          .main__section5__center__box__logo
          .main__section5__center__box__logo1
                    
  = render "footer"

  = render "shuppin"

app/views/items/search.html.haml
.search
  .search__main
    .search__main__inner
      .search__main__inner__icon
        = link_to root_path do
          = image_tag "logo/logo.png"
      .search__main__inner__key
      = form_with(url: search_items_path, local: true, method: :get) do |s|
        = s.text_field :keyword, placeholder: "キーワードから探す", class: "search__main__inner__key__search"
        = s.submit "i", class: "search__main__inner__key__submit"
        = icon("fa", "search", class: "search__main__inner__key__icon") 
      
    .login__main__bottom
      .login__main__bottom__left
        %ul.login__main__bottom__left__ul
          %li.login__main__bottom__left__ul__list1
            = link_to 'カテゴリー', categories_path, id: 'catBtn'
            = render  "items/nav-category", parent: @parents
          %li.login__main__bottom__left__ul__list
            = link_to 'ブランド', '#', id: 'brandBtn'
      - if user_signed_in?
        .login__main__bottom__right
          %ul.login__main__bottom__right__ul
            %li.login__main__bottom__right__ul__list 
          = link_to "マイページ", users_path
      - else
        .search__main__bottom__right
          %ul.search__main__bottom__right__ul
            %li.search__main__bottom__right__ul__list 
            = link_to "ログイン", new_user_session_path
            %li.search__main__bottom__right__ul__list 
            = link_to "新規登録", new_user_registration_path
    - @items.each do |item|
      .search__section4__box__main__product__lists1
        -if item.buyer_id.present? 
          .search-box_photo__sold
            .search-box_photo__sold__inner
              SOLD
        .search__section4__box__main__product__lists1__image
          = link_to item_path "#{item.id}" do
            = image_tag "#{item.images.first.image}"
          .search__section4__box__main__product__lists1__list
            .search__section4__box__main__product__lists1__list__text
              = item.name
            .search__section4__box__main__product__lists1__list__text1 
              .search__section4__box__main__product__lists1__list__text1__left
                = item.price
                円
              .search__section4__box__main__product__lists1__list__text1__right ★ 0
            .search__section4__box__main__product__lists1__list__text2 (税込み)

app/views/items/show.html.haml
= render "header"
%nav.breadCrumbs
  %ul.path-list
    %li.path-list__1
      = link_to root_path do
        FURIMA
    %li.path-list__2
      %i.fa.fa-angle-right
    %li.path-list__3
      = link_to "#" do
        = @item.category.root.name
    %li.path-list__4
      %i.fa.fa-angle-right
    %li.path-list__5
      = link_to "#" do
        = @item.category.parent.name
    %li.path-list__6
      %i.fa.fa-angle-right
    %li.path-list__7
      = link_to "#" do 
        = @item.category.name
    %li.path-list__8
      %i.fa.fa-angle-right
    %li.path-list__9
      %p 
        = @item.name
.mainshow
  .showMain
    .content
      - breadcrumb :shower
      = breadcrumbs separator: " &rsaquo; "
      .topcontent
        .itemBox
          %h2.itemBox__name
            = @item.name
          .itemBox__body
            %ul.item-image
              = image_tag "#{@item.images.first.image}", class:'top-picture', height: '180px', width: '400px'
              %ul.sub-image 
                - @item.images.each do |item|
                  %li.main-image
                    = image_tag "#{item.image}"
          .itemBox__price 
            = @item.price
            .itemBox__price-detail
              %span (税込み)
              %span 送料込み
          - if user_signed_in? && current_user.id == @item.seller_id 
            .itemBox__main
              .itemBox__main__edit
                = link_to '編集する', edit_item_path(@item.id)
              .itemBox__main__destroy
                = link_to item_path(@item), method: :delete, data: { disable_with: '問い合わせ中...' } do
                  削除する
            .itemDetail
              = @item.description
            .table
              %table
                %tbody
                  %tr
                    %th 出品者
                    %td 
                      = @user.nickname
                  %tr
                    %th カテゴリー
                    %td
                      = link_to "#" do
                        = @item.category.root.name
                      %br
                      = link_to "#" do
                        = @item.category.parent.name
                      %br
                      = link_to "#" do
                        = @item.category.name
                  %tr
                    %th ブランド
                    %td 
                      = @item.brand
                  %tr
                    %th 商品のサイズ 
                    %td
                      = @item.size
                  %tr
                    %th 商品の状態
                    %td 
                      = @item.condition
                  %tr
                    %th 配送料の負担
                    %td 
                      = @item.delivery_charge
                  %tr
                    %th 発送元地域
                    %td 
                      = @item.prefecture.name
                  %tr
                    %th 発送日の目安
                    %td 
                      = @item.delivery_day
            .optionalArea
              %ul
                %li#likeBtn.optionalBtn.likeBtn
                  %i.fa.fa-star
                  お気に入り 0
              %ul.optional
                %li.optionalBtn
                  = link_to "#" do
                    %i.fa.fa-flag
                      不適切な商品の通報

          - elsif @item.buyer_id
            .itemBox__sold
              .itemBox__sold__box Sold Out
            .itemDetail
              = @item.description
            .table
              %table
                %tbody
                  %tr
                    %th 出品者
                    %td 
                      = @user.nickname
                  %tr
                    %th カテゴリー
                    %td
                      = link_to "#" do
                        = @item.category.root.name
                      %br
                      = link_to "#" do
                        = @item.category.parent.name 
                      %br
                      = link_to "#" do
                        = @item.category.name
                  %tr
                    %th ブランド
                    %td 
                      = @item.brand
                  %tr
                    %th 商品のサイズ 
                    %td
                      = @item.size
                  %tr
                    %th 商品の状態
                    %td 
                      = @item.condition
                  %tr
                    %th 配送料の負担
                    %td 
                      = @item.delivery_charge
                  %tr
                    %th 発送元地域
                    %td 
                      = @item.prefecture.name
                  %tr
                    %th 発送日の目安
                    %td 
                      = @item.delivery_day
            .optionalArea
              %ul
                %li#likeBtn.optionalBtn.likeBtn
                  %i.fa.fa-star
                  お気に入り 0
              %ul.optional
                %li.optionalBtn
                  = link_to "#" do
                    %i.fa.fa-flag
                      不適切な商品の通報

          - else    
            .itemBox__button
              = link_to '購入画面へ進む', item_buycheck_path(@item) ,class:"itemBox__button__text"
            .itemDetail
              = @item.description
            .table
              %table
                %tbody
                  %tr
                    %th 出品者
                    %td 
                      = @user.nickname
                  %tr
                    %th カテゴリー
                    %td
                      = link_to "#" do
                        = @item.category.root.name
                      %br
                      = link_to "#" do
                        = @item.category.parent.name 
                      %br
                      = link_to "#" do
                        = @item.category.name
                  %tr
                    %th ブランド
                    %td 
                      = @item.brand
                  %tr
                    %th 商品のサイズ 
                    %td
                      = @item.size
                  %tr
                    %th 商品の状態
                    %td 
                      = @item.condition
                  %tr
                    %th 配送料の負担
                    %td 
                      = @item.delivery_charge
                  %tr
                    %th 発送元地域
                    %td 
                      = @item.prefecture.name
                  %tr
                    %th 発送日の目安
                    %td 
                      = @item.delivery_day
            .optionalArea
              %ul
                %li#likeBtn.optionalBtn.likeBtn
                  %i.fa.fa-star
                  お気に入り 0
              %ul.optional
                %li.optionalBtn
                  = link_to "#" do
                    %i.fa.fa-flag
                      不適切な商品の通報
                      
        .commentBox
          %ul.commentContents
          %form.new_comment
            %input{type: "text"}
            %p.noticeMsg
              相手のことを考え丁寧なコメントを心がけましょう。
              %br
              不快な言葉遣いなどは利用制限や退会処分となることがあります。
            %br
            %button{name: "button", type: "submit", class: "commentBtn"}
              %i.fa.fa-comment
                コメントする
      %ul.links
        %li
          = link_to "#" do
            %i.fa.fa-angle-left
            %span
              前の商品
        %li
          = link_to "#" do
            %span 後ろの商品
            %i.fa.fa-angle-right
      .relatedItems
        = link_to "#" do
          レディースをもっとみる
      .productlists

   
.main__section5
  .main__section5__center
    %h1.main__section5__center__h1 だれでもかんたん、人生を変えるフリマアプリ
    %p.main__section5__center__p1 
      今すぐ無料ダウンロード
      .main__section5__center__box
        .main__section5__center__box__logo
        .main__section5__center__box__logo1

= render "footer"

= render "shuppin"