config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'items#index'
  resources :items do
    get '/buycheck', controller: 'items', action: 'buycheck'
    post '/payment', controller: 'items', action: 'payment'
    #Ajaxで動くアクションのルートを作成
    collection do
      get 'category' 
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
    end
  end
  resources :users, only: :index
  get 'users/:name', controller: 'users', action: 'show'
  get 'users/:name', controller: 'users', action: 'edit'
  
  resources :card, only: [:index, :new, :show, :destroy] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
    end
  end
  resources :categories, only: :index

end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user, optional: true

  validates :user_id, presence: true
  validates :customer_id, presence: true
  validates :card_id, presence: true
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  require 'payjp'

  def index
    card = Card.where(user_id: current_user.id)
    redirect_to action: :show if card.exists?
  end

  def new
  end

  def pay
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_PRIVATE_KEY)
    if params['payjp-token'].blank?
      redirect_to action: :new
    else
      customer = Payjp::Customer.create(
        email: current_user.email,
        card: params['payjp-token'],
        metadata: {user_id: current_user.id}
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to controller: :card, action: :show
      else
        redirect_to action: "pay"
      end
    end
  end

  def destroy
    card = Card.find_by(card_id: params[:id])
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_PRIVATE_KEY)
    customer = Payjp::Customer.retrieve(card.customer_id)
    customer.delete
    card.destroy
    redirect_to action: :index
  end

  def show
    redirect_to action: :index unless current_user.cards.present?
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_PRIVATE_KEY)
    customer = Payjp::Customer.retrieve(current_user.cards.first.customer_id)
    @default_card_information = customer.cards.retrieve(current_user.cards.first.card_id)
    customer2 = Payjp::Customer.retrieve(current_user.cards.last.customer_id) if current_user.cards.count == 2
    @second_card_information = customer2.cards.retrieve(current_user.cards.last.card_id) if current_user.cards.count == 2
  end

end

app/helpers/card_helper.rb
module CardHelper
end

app/views/card/index.html.haml
.wrapper
  = render "items/header"
  .mainview
    = render "users/side"
    .show-card
      .show-card__contents
        .show-card__contents_head
          %p カード情報
        .show-card__contents_payment
          .show-card__contents_payment_head
            %p クレジットカード一覧
          .show-card__contents_payment_list
            %p ※クレジットカード情報がありません
          .show-card__contents_payment_create
            = link_to new_card_path, class: "card__create-btn", data: {"turbolinks" => false} do
              %p 追加する
  = render "items/footer"

app/views/card/new.html.haml
.wrapper
  = render "items/header"
  .mainview
    = render "users/side"
    .create-card
      .create-card__contents
        .create-card__contents_head
          %p カード情報登録
        .create-card__contents_form
          = form_tag(pay_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
            .create-card__content
              .create-card__content_num
                .create-card__content_num_title
                  %p カード番号
                .create-card__content_num_form
                  = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
              .create-card__content_limit
                .create-card__content_limit_title
                  %p 有効期限
                .create-card__content_limit_form
                  %select#exp_month{name: "exp_month", type: "text"}
                    %option{value: ""} --
                    %option{value: "1"}01
                    %option{value: "2"}02
                    %option{value: "3"}03
                    %option{value: "4"}04
                    %option{value: "5"}05
                    %option{value: "6"}06
                    %option{value: "7"}07
                    %option{value: "8"}08
                    %option{value: "9"}09
                    %option{value: "10"}10
                    %option{value: "11"}11
                    %option{value: "12"}12
                  %span 月/
                  %select#exp_year{name: "exp_year", type: "text"}
                    %option{value: ""} --
                    %option{value: "2019"}19
                    %option{value: "2020"}20
                    %option{value: "2021"}21
                    %option{value: "2022"}22
                    %option{value: "2023"}23
                    %option{value: "2024"}24
                    %option{value: "2025"}25
                    %option{value: "2026"}26
                    %option{value: "2027"}27
                    %option{value: "2028"}28
                    %option{value: "2029"}29
                  %span 年
              .create-card__content_cvc
                .create-card__content_cvc_title
                  %p セキュリティコード
                .create-card__content_cvc_form
                  = text_field_tag "cvc", "", class: "cvc", placeholder: "CVC", maxlength: "4", id: "cvc"
                  %p ※カード背面の３〜４桁の番号です
              #card_token
              = submit_tag "追加する", id: "token_submit"
  = render "items/footer"

app/views/card/show.html.haml
.wrapper
  = render "items/header"
  .mainview
    = render "users/side"
    .show-card
      .show-card__contents
        .show-card__contents_head
          %p カード情報
        .show-card__contents_payment
          .show-card__contents_payment_head
            %p クレジットカード一覧
          .show-card__contents_payment_list
            .card__payment_list
              .card__payment_list_image
              .card__payment_list_number
                = "**** **** ****" + @default_card_information.last4
              .card__payment_list_data
                - exp_month = @default_card_information.exp_month.to_s
                - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                = exp_month + " / " + exp_year
              .card__payment_list_delete-btn
                = form_tag(card_path(id: @default_card_information.id), method: :delete, id: 'charge-form',  name: "inputForm") do
                  %input{ type: "hidden", name: "card_id", value: "" }
                  %button 削除する
          - if @second_card_information.present?
            .card-sec__payment_list
              .card-sec__payment_list_image
              .card-sec__payment_list_number
                = "**** **** ****" + @second_card_information.last4
              .card-sec__payment_list_data
                - exp_month = @second_card_information.exp_month.to_s
                - exp_year = @second_card_information.exp_year.to_s.slice(2,3)
                = exp_month + " / " + exp_year
              .card-sec__payment_list_delete-btn
                = form_tag(card_path(id: @second_card_information.id), method: :delete, id: 'charge-form',  name: "inputForm") do
                  %input{ type: "hidden", name: "card_id", value: "" }
                  %button 削除する
          .show-card__contents_payment_create
            - if @second_card_information.blank?
              = link_to new_card_path, class: "card__create-btn", data: {"turbolinks" => false} do
                %p 追加する
            - else
              %p ※２つまでしか登録できません
  = render "items/footer"